### ISSUE TITLE
The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by Unconquered1** [GeorgeSchiro/GetCert2#1]
[GetCert2.exeLog-2019-12-27.txt](https://github.com/GeorgeSchiro/GetCert2/files/4005881/GetCert2.exeLog-2019-12-27.txt)

I keep getting this error when running GetCert2 "The remote server returned an error: (404) Not Found." 

Which then leads to "+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException" 

and then the result is "GetCertServiceFault: The sub-process experienced a critical failure"
(please see attached)

Is this an bug or am I doing something incorrectly?

**Comment by supportsiden** [comment]
I see the excact same error. Please provide a solution

**Comment by GeorgeSchiro** [comment]
Please accept my apologies. For whatever reason, I did not get an email from Unconquered1's issue.

@Unconquered1, from your log I can see the challenge URL was this:

    http://marketingpreview.previdence.com/.well-known/acme-challenge/mCrHnbozj7hQZrvNWY4pdP2MtbWmQ_VX98v-BXGh9pM

Sadly, that location on your server appears not to be accessible. Looks like "http" (ie. port 80) is not getting through (ie. there's a redirect to port 443). This won't work with ACME.

@supportsiden, is that possibly your issue as well?

**Comment by GeorgeSchiro** [comment]
Before I close this issue, let me restate the resolution.

The ACME protocol requires port 80 to be open on whatever server is communicating with the Let's Encrypt service. Automatic redirects from port 443 to port 80 is equivalent to not having port 80 open.

Please disable the automatic redirects to SSL and try again.

Remember, if you can't get to the challenge URL via your own web browser, neither can Let's Encrypt. That means they can't confirm it's really your domain.

**Comment by Unconquered1** [comment]
Hi George, sorry for my late response. Thank you for taking the time to respond. I truly appreciate the fact that your time is important and that you did not need to respond to me. 
2 problems with this solution to the  issue. 1) I did not have the 443 only URL rule implementation on at the time of this issue. 2) Other ACME solutions that integrate with letsencrypt.org do not have this same problem.   Although, I found another way to get my certificates you may want to look into the issue for others.  Thank you again.

**Comment by GeorgeSchiro** [comment]
Thank you for this feedback Hank. I am very interested in understanding this issue better, but going back-and-forth here is not the best way for quick resolution, IMHO. We can report back to this forum once we know exactly what's really going on.

Please email me: BetaHelp at SafeTrust.org . I will reply with my phone number (or you can do the same in your email). Walking through this issue over the phone would be most helpful I think. I look forward to hearing from you.

**Comment by GeorgeSchiro** [comment]
Not sure if you guys have moved on or not, but I just noticed something that might account for the behavior you are seeing.

Depending on how your network is setup, a process running on your web server may not be able "to see itself" (ie. requests to your website from the web server itself may not work). You may need a loopback entry (ie. 127.0.0.1) in your local "hosts" file.

You can prove this by removing a line of code from the -ScriptStage3 snippet (see "GetCert2.exe.config"). Look for this:

    $challenge.Data.AbsoluteUrl
    Invoke-WebRequest $challenge.Data.AbsoluteUrl
    $challenge | Complete-ACMEChallenge $global:state

Replace it with this:

    $challenge.Data.AbsoluteUrl
    #Invoke-WebRequest $challenge.Data.AbsoluteUrl
    $challenge | Complete-ACMEChallenge $global:state

The "Invoke-WebRequest" is not really needed. It's actually overkill to verify the challenge URL really exists and can be seen by Let's Encrypt. I think we will remove it from the next release.
