### ISSUE TITLE
Cert2 IIS Site path paramter?

### ISSUE THREAD

**Issue by SuperlativeIT** [GeorgeSchiro/GetCert2#10]
We’re looking to replace our v1 Acme Simple client and ran into your implementation however we seem to be at a loss as to how to specify the physical folder path for which the IIS site entry points to as we don’t use the C:\Inetpub\wwwroot in our environment. Is there a parameter we can pass to GetCert2.exe to allow us to specify the domain name IIS site folder location?

Thank You

Sincerely,

**Comment by GeorgeSchiro** [comment]
GetCert2 is meant to be a simple client as well. For that reason, it expects to find an existing site to copy from whenever a new site does not yet exist for the given certificate subject name.

The typical scenario (when a site needs to be created on-the-fly) is when a new SAN value is provided for a primary domain that already has a site defined. In that case, the new SAN site gets a copy of the physical path found in the primary site.

Alternatively, if no related site is found during the "get cert" process, the default website will be selected and the physical folder found there will be used for the newly created site. Can you adjust the  physical folder parameter found in the default website before the process runs to get your new cert?

Finally, if no default site is found, the value of -DefaultPhysicalPath (found in the profile) will be used.

**Comment by SuperlativeIT** [comment]
Thank you for the explanation. I will pass the info over to our developer.
