### ISSUE TITLE
-SanList Command Line Option Syntax

### ISSUE THREAD

**Issue by kiwiingenuity** [GeorgeSchiro/GetCert2#2]
In the documentation can I suggest under  -SanList option
you provide the example.
-SanList="-Domain=example.com -Domain=www.example.com"

**Comment by GeorgeSchiro** [comment]
Good suggestion. Will do.

BTW, when GetCert2 runs to completion you will notice snippets of "ACME-PS" script embedded in the log file. That should give you everything you need to understand how to handle a SAN list via "ACME-PS" directly.

**Comment by kiwiingenuity** [comment]
Looking at the log file for the snippets would be great....
I'm yet to run successfully to the completion??
