### ISSUE TITLE
Command Line -ini

### ISSUE THREAD

**Issue by kiwiingenuity** [GeorgeSchiro/GetCert2#3]
I could not get GetCert2.exe -ini=NewProfile.txt to work for me as shown in your documentation

However I could get GetCert2.exe -ini="NewProfile.txt"
to work.

**Comment by GeorgeSchiro** [comment]
This works for me:

    GetCert2.exe -ini=NewProfile.txt

You must start with an existing profile file. Try copying the default "GetCert2.exe.config" to "NewProfile.txt". Be sure to include a -ContactEmailAddress value in the profile.

When you run GetCert2.exe with no arguments, the default profile will be used. Run it with the above -ini arg and it will use "NewProfile.txt" instead.
