### ISSUE TITLE
IIS Site name

### ISSUE THREAD

**Issue by kiwiingenuity** [GeorgeSchiro/GetCert2#4]
Does your application assume that the IIS Name for a site must be the same as the -CertificateDomainName?
If so how do we overide this?

**Comment by GeorgeSchiro** [comment]
No. For example, the IIS "Default Web Site" is typical. There is no problem getting certs for it. That said, if "Default Web Site" already has a bound cert and the name on a new cert does not match, a new site will be created for the new cert. This behavior can be overridden using the -CreateSanSites switch (ie. -CreateSanSites=False).

Basically, the software looks at bound certs first (to determine where a new cert goes) and then site names.

**Comment by kiwiingenuity** [comment]
In my case: 
	1. My "Default Web Site is not running".
	2. The "Default Web Site" does not have a bound certificate.
	3. Your application is not seeing the currently registered certificate. I suspect this is because I have them in a folder called "Web Hosting" instead of the "Personal" folder in the Certificates Console.
	
	My Cmdline is 
	GetCert2.exe -CertificateDomainName="example.com" -SanList="-Domain=example.com -Domain=www.example.com" -RemoveReplacedCert=True -ContactEmailAddress="me@mydomain.com" -CreateSanSites=False
	
	Looking at the log at Stage 3 the $challengePath is defaulting to the "Default Web Site" and not the path where the website resides.

**Comment by GeorgeSchiro** [comment]
1. NP.
2. NP.
3. You're right!

Look for "public static X509Certificate2Collection oCurrentCertificateCollection()"), it looks for old certificates in the "Local Computer / Personal / Certificates" store.  You can add old certs from anywhere else into the same collection before it's returned.

Bind an old certificate (one with a name that matches the new cert you are trying to get) to whatever site is running. GetCert2 should be able to find it.

**Comment by kiwiingenuity** [comment]
OK, that partially worked!
Moving the certificate to "Personal", enabled the challenge to work! But only for "example.com" and not "www"
Again I can understand this is because I'm doing something a little be different.....
The old certificate was only for "example.com".  
I wanted to create a new certificate for "example.com" and "www.example.com"
As the situation stands at the moment the Challenge for "example.com" is successful, but the challenge for "www.example.com" looks in the "Default Web Site Path".
Your thoughts?

**Comment by GeorgeSchiro** [comment]
You need a separate site for each SAN in the list. That's how ACME challenges work, one per SAN. That's why the -CreateSanSites switch is true by default. Try letting it create the site. You can either use it after that or delete it.
