### ISSUE TITLE
Provide a ready to use exe file

### ISSUE THREAD

**Issue by enachi** [GeorgeSchiro/GetCert2#7]
Hi 

Please provide download links for the GetCert2.exe
also, maybe  you wanna reduce the readme page, and provide more datails for example on a wiki page?

Thanks

**Comment by GeorgeSchiro** [comment]
It's in there:

    https://github.com/GeorgeSchiro/GetCert2/blob/master/GetCertClient/bin/Release/GetCert2.exe
