### ISSUE TITLE
Tool does not recognise new TLD

### ISSUE THREAD

**Issue by asacic** [GeorgeSchiro/GetCert2#8]
Hi, 

when typing in a TLD longer than 4 characters, the tool detects the input as invalid.
Therefore. please  change 
```
Regex loEmailRegex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,9})$");
Regex loDnsNameRegex = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,9}$"); 
```
to
```
Regex loEmailRegex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z{2,20})$");
Regex loDnsNameRegex = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,20}$");
```

Also change
```
Regex loDnsNameRegex = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,4}$");
```
to
```
Regex loDnsNameRegex = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,20}$");
```

This ensures that also the long new TLDs work. 
Thanks!

**Comment by GeorgeSchiro** [comment]
Thank you Amir! This was actually brought to our attention earlier this week. Here's what we wrote Tuesday:

Mike, we expect to have a new major release available by this weekend (GetCert2 version 2.0, including the following changes).
 
In the mean time, in "UI.xaml.cs" you can replace this (look for "bValidateConfigWizardValues()"):
 
            Regex loEmailRegex   = new Regex(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$");
            Regex loDnsNameRegex = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,4}$");
    with this:
            Regex loEmailRegex   = new Regex(moProfile.sValue("-RegexEmailAddress", @"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$"));
            Regex loDnsNameRegex = new Regex(moProfile.sValue("-RegexDnsNamePrimary", @"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,7}$"));

It would also be a good idea (for the sake of completeness) for you to replace this (look for "bValidateConfigWizardSanList()"):
 
            Regex loDnsNameRegex  = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,4}$");
            Regex loDnsNameRegex2 = new Regex(@"^[^.][\*a-zA-Z0-9\-\.]+\.$");
    with this:
            Regex loDnsNameRegex  = new Regex(moProfile.sValue("-RegexDnsNamePrimary", @"^[^.][\*a-zA-Z0-9\-\.]+\.[a-zA-Z0-9]{2,7}$"));
            Regex loDnsNameRegex2 = new Regex(moProfile.sValue("-RegexDnsNameSanList", @"^[^.][\*a-zA-Z0-9\-\.]+\.$"));

    FYI, it's the "moProfile.sValue()" references that now make this regex stuff configurable.
 
Alternatively, you can chuck what you have and start over with the new version (hopefully by Monday at the latest).

**Comment by GeorgeSchiro** [comment]
BTW, I just realized that your post referenced the email expression as well. We were only thinking about DNS names for the certificates, not for the contact email. 

We've made that adjustment as well (we compromised on max length - yours is 9 ours is 7, but configurable. Hope that's works for you.

Thanks again Amir!

**Comment by asacic** [comment]
Don't worry about the length. I've recompiled it for my needs. :)

If you look at the list of all TLDs you'll see longer TLD's (.accountants for instance). Maybe a thing to consider.

http://data.iana.org/TLD/tlds-alpha-by-domain.txt

Thanks!
________________________________

**Comment by GeorgeSchiro** [comment]
We know there are longer names. We settled on a default max of 7 (eg. ".systems") since that's what Mike was looking for. 👍
